/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_Red */
#define LED_Red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_0_INBUF_ENABLED 0u
#define LED_Red_0_INIT_DRIVESTATE 1u
#define LED_Red_0_INIT_MUXSEL 0u
#define LED_Red_0_INPUT_SYNC 2u
#define LED_Red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_0_NUM 3u
#define LED_Red_0_PORT GPIO_PRT0
#define LED_Red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_INBUF_ENABLED 0u
#define LED_Red_INIT_DRIVESTATE 1u
#define LED_Red_INIT_MUXSEL 0u
#define LED_Red_INPUT_SYNC 2u
#define LED_Red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_NUM 3u
#define LED_Red_PORT GPIO_PRT0
#define LED_Red_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* SW_P0_4 */
#define SW_P0_4_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define SW_P0_4_0_INBUF_ENABLED 1u
#define SW_P0_4_0_INIT_DRIVESTATE 1u
#define SW_P0_4_0_INIT_MUXSEL 0u
#define SW_P0_4_0_INPUT_SYNC 2u
#define SW_P0_4_0_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define SW_P0_4_0_NUM 4u
#define SW_P0_4_0_PORT GPIO_PRT0
#define SW_P0_4_0_SLEWRATE CY_GPIO_SLEW_FAST
#define SW_P0_4_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define SW_P0_4_DRIVEMODE CY_GPIO_DM_PULLUP
#define SW_P0_4_INBUF_ENABLED 1u
#define SW_P0_4_INIT_DRIVESTATE 1u
#define SW_P0_4_INIT_MUXSEL 0u
#define SW_P0_4_INPUT_SYNC 2u
#define SW_P0_4_INTERRUPT_MODE CY_GPIO_INTR_FALLING
#define SW_P0_4_NUM 4u
#define SW_P0_4_PORT GPIO_PRT0
#define SW_P0_4_SLEWRATE CY_GPIO_SLEW_FAST
#define SW_P0_4_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
