/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* Pin_1 */
#define Pin_1_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_0_INBUF_ENABLED 0u
#define Pin_1_0_INIT_DRIVESTATE 1u
#define Pin_1_0_INIT_MUXSEL 0u
#define Pin_1_0_INPUT_SYNC 2u
#define Pin_1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_0_NUM 4u
#define Pin_1_0_PORT GPIO_PRT10
#define Pin_1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_1_DRIVEMODE CY_GPIO_DM_ANALOG
#define Pin_1_INBUF_ENABLED 0u
#define Pin_1_INIT_DRIVESTATE 1u
#define Pin_1_INIT_MUXSEL 0u
#define Pin_1_INPUT_SYNC 2u
#define Pin_1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_1_NUM 4u
#define Pin_1_PORT GPIO_PRT10
#define Pin_1_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_Blue */
#define LED_Blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_0_INBUF_ENABLED 0u
#define LED_Blue_0_INIT_DRIVESTATE 1u
#define LED_Blue_0_INIT_MUXSEL 0u
#define LED_Blue_0_INPUT_SYNC 2u
#define LED_Blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_0_NUM 1u
#define LED_Blue_0_PORT GPIO_PRT11
#define LED_Blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_INBUF_ENABLED 0u
#define LED_Blue_INIT_DRIVESTATE 1u
#define LED_Blue_INIT_MUXSEL 0u
#define LED_Blue_INPUT_SYNC 2u
#define LED_Blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_NUM 1u
#define LED_Blue_PORT GPIO_PRT11
#define LED_Blue_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Pin_SW_2 */
#define Pin_SW_2_0_DRIVEMODE CY_GPIO_DM_PULLUP
#define Pin_SW_2_0_INBUF_ENABLED 1u
#define Pin_SW_2_0_INIT_DRIVESTATE 1u
#define Pin_SW_2_0_INIT_MUXSEL 0u
#define Pin_SW_2_0_INPUT_SYNC 2u
#define Pin_SW_2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_SW_2_0_NUM 4u
#define Pin_SW_2_0_PORT GPIO_PRT0
#define Pin_SW_2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_SW_2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Pin_SW_2_DRIVEMODE CY_GPIO_DM_PULLUP
#define Pin_SW_2_INBUF_ENABLED 1u
#define Pin_SW_2_INIT_DRIVESTATE 1u
#define Pin_SW_2_INIT_MUXSEL 0u
#define Pin_SW_2_INPUT_SYNC 2u
#define Pin_SW_2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Pin_SW_2_NUM 4u
#define Pin_SW_2_PORT GPIO_PRT0
#define Pin_SW_2_SLEWRATE CY_GPIO_SLEW_FAST
#define Pin_SW_2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
