# -*- coding: utf-8 -*-
"""Lab4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZQVS6FeqZy4PvsOzxsjjNobIcHSd4RmR
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Завантаження файлу
df = pd.read_excel('/4_10.xlsx')

# Імена колонок
df.columns = ["x1", "x2", "label"]

df.head()

X = df[["x1", "x2"]].values
y = df["label"].values

scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

X_train, X_test, y_train, y_test = train_test_split(
    X_scaled, y, test_size=0.3, shuffle=True, random_state=42
)

plt.figure(figsize=(7,7))
for cls, color in zip([0,1,2], ['red','green','blue']):
    pts = X_train[y_train == cls]
    plt.scatter(pts[:,0], pts[:,1], s=10, color=color, label=f"Class {cls}")

plt.title("Навчаючі дані (після нормування)")
plt.grid(True)
plt.legend()
plt.show()

num_classes = 3
W = np.random.randn(num_classes, 3) * 0.01   # (3 виходи × (2 входи + bias))
lr = 0.05
epochs = 1500

def softmax(z):
    exp = np.exp(z - np.max(z))
    return exp / exp.sum()

def forward(x):
    x_ext = np.append(x, 1)
    return softmax(W @ x_ext)

losses = []

for ep in range(epochs):
    loss = 0
    for xi, ti in zip(X_train, y_train):

        x_ext = np.append(xi, 1)
        y_pred = softmax(W @ x_ext)

        T = np.zeros(num_classes)
        T[ti] = 1

        error = T - y_pred

        for k in range(num_classes):
            W[k] += lr * error[k] * x_ext

        loss += np.sum((T - y_pred)**2)

    losses.append(loss)

print("Навчання завершено.")

def predict(x):
    return np.argmax(forward(x))

y_pred = np.array([predict(x) for x in X_test])
general_accuracy = np.mean(y_pred == y_test) * 100

print(f"Загальна точність класифікації: {general_accuracy:.2f}%")

for cls in [0,1,2]:
    idx = (y_test == cls)
    acc = np.mean(y_pred[idx] == cls) * 100
    print(f"Точність класу {cls}: {acc:.2f}%")

    plt.figure(figsize=(7,7))
colors = ['red','green','blue']

for cls in [0,1,2]:
    pts = X_test[y_pred == cls]
    plt.scatter(pts[:,0], pts[:,1], s=10, color=colors[cls], label=f"Predicted {cls}")

plt.title("Результат класифікації тестових точок")
plt.legend()
plt.grid(True)
plt.show()