/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* LED_Red */
#define LED_Red_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_0_INBUF_ENABLED 0u
#define LED_Red_0_INIT_DRIVESTATE 1u
#define LED_Red_0_INIT_MUXSEL 8u
#define LED_Red_0_INPUT_SYNC 2u
#define LED_Red_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_0_NUM 3u
#define LED_Red_0_PORT GPIO_PRT0
#define LED_Red_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Red_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Red_INBUF_ENABLED 0u
#define LED_Red_INIT_DRIVESTATE 1u
#define LED_Red_INIT_MUXSEL 8u
#define LED_Red_INPUT_SYNC 2u
#define LED_Red_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Red_NUM 3u
#define LED_Red_PORT GPIO_PRT0
#define LED_Red_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Red_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_Blue */
#define LED_Blue_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_0_INBUF_ENABLED 0u
#define LED_Blue_0_INIT_DRIVESTATE 1u
#define LED_Blue_0_INIT_MUXSEL 9u
#define LED_Blue_0_INPUT_SYNC 2u
#define LED_Blue_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_0_NUM 1u
#define LED_Blue_0_PORT GPIO_PRT11
#define LED_Blue_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Blue_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Blue_INBUF_ENABLED 0u
#define LED_Blue_INIT_DRIVESTATE 1u
#define LED_Blue_INIT_MUXSEL 9u
#define LED_Blue_INPUT_SYNC 2u
#define LED_Blue_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Blue_NUM 1u
#define LED_Blue_PORT GPIO_PRT11
#define LED_Blue_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Blue_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* LED_Green */
#define LED_Green_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Green_0_INBUF_ENABLED 0u
#define LED_Green_0_INIT_DRIVESTATE 1u
#define LED_Green_0_INIT_MUXSEL 8u
#define LED_Green_0_INPUT_SYNC 2u
#define LED_Green_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Green_0_NUM 1u
#define LED_Green_0_PORT GPIO_PRT1
#define LED_Green_0_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Green_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define LED_Green_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define LED_Green_INBUF_ENABLED 0u
#define LED_Green_INIT_DRIVESTATE 1u
#define LED_Green_INIT_MUXSEL 8u
#define LED_Green_INPUT_SYNC 2u
#define LED_Green_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define LED_Green_NUM 1u
#define LED_Green_PORT GPIO_PRT1
#define LED_Green_SLEWRATE CY_GPIO_SLEW_FAST
#define LED_Green_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
