# -*- coding: utf-8 -*-
"""lab6_7_clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19rNWDD_kShaZ6nfEfSVKi5HWAD0EQJjC

# Lab 6_7 Clustering
"""

# Full lab code: clustering lab (classical simple algorithm, K-means variants, Kohonen-like NN)
# Paste this entire block into a Google Colab cell and run.
# Requirements: pandas, numpy, matplotlib, sklearn (all installed in Colab by default)

import os
import math
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score
from sklearn.preprocessing import StandardScaler, normalize
from sklearn.decomposition import PCA

# ----------------------------
# User-adjustable parameters
# ----------------------------
EXCEL_PATHS = [
    "/content/Лаб6_7_6_кластер.xlsx",
    "/content/Завдання_Лаб6_файл№.xlsx",
    "/mnt/data/Лаб6_7_6_кластер.xlsx",
    "/mnt/data/Лаб6_7_6_кластер.xlsx",
    "Лаб6_7_6_кластер.xlsx"
]
SHEET_NAME = 0  # or name
FEATURE_COLS = None  # None => use all numeric columns
ID_COL = None  # optional id column name

# Experiment parameters
K = 3  # target number of clusters for K-means and Kohonen (set according to your task)
T_values = np.linspace(0.5, 3.0, 10)  # threshold sweep (classical algorithm)
KMEANS_REPEATS = 10  # how many random restarts for each init strategy
KOHO_EPOCHS = 200
KOHO_LR0 = 0.1
KOHO_DECAY = 0.995
RANDOM_STATE = 42
SAVE_RESULTS_DIR = "/content/clustering_results"

os.makedirs(SAVE_RESULTS_DIR, exist_ok=True)
np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

# ----------------------------
# Utilities
# ----------------------------
def try_load_excel(paths):
    for p in paths:
        if os.path.isfile(p):
            print(f"Loading Excel file: {p}")
            try:
                df = pd.read_excel(p, sheet_name=SHEET_NAME)
                return df, p
            except Exception as e:
                print("Failed to read", p, e)
    return None, None

def prepare_features(df, feature_cols=None):
    df_num = df.select_dtypes(include=[np.number]).copy()
    if feature_cols is not None:
        df_num = df_num[feature_cols]
    return df_num

def ensure_2d(X):
    X = np.asarray(X)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    return X

def save_fig(fig, name):
    path = os.path.join(SAVE_RESULTS_DIR, name)
    fig.savefig(path, bbox_inches="tight")
    print(f"Saved figure: {path}")

def plot_2d(X, labels=None, centers=None, title="", save_name=None):
    fig, ax = plt.subplots(figsize=(6,5))
    if labels is None:
        ax.scatter(X[:,0], X[:,1], s=30)
    else:
        unique = np.unique(labels)
        for u in unique:
            mask = labels == u
            ax.scatter(X[mask,0], X[mask,1], s=30, label=f"c{u}")
        ax.legend()
    if centers is not None:
        ax.scatter(centers[:,0], centers[:,1], marker='X', s=150, c='k', label='centers')
        ax.legend()
    ax.set_title(title)
    if save_name:
        save_fig(fig, save_name)
    plt.show()

# ----------------------------
# Data loading
# ----------------------------
df, loaded_path = try_load_excel(EXCEL_PATHS)

if df is None:
    print("No Excel data found in expected paths. Generating synthetic example data (3 clusters).")
    # create example 2D dataset for demonstration
    from sklearn.datasets import make_blobs
    X, y_true = make_blobs(n_samples=150, centers=3, cluster_std=[0.6, 0.4, 0.5], random_state=RANDOM_STATE)
    df = pd.DataFrame(X, columns=["x1","x2"])
    data_label = "synthetic"
else:
    df_num = prepare_features(df, FEATURE_COLS)
    # If dataset has more than 2 dims, we'll later reduce to 2D for plotting using PCA
    X = df_num.values
    df = df_num.reset_index(drop=True)
    data_label = os.path.basename(loaded_path)

X = ensure_2d(X)
n_samples, n_features = X.shape
print(f"Data: {data_label} | samples={n_samples}, features={n_features}")

# Standardize for methods that benefit from scaling
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# For plotting, create a 2D projection
if n_features > 2:
    pca = PCA(n_components=2, random_state=RANDOM_STATE)
    X_2d = pca.fit_transform(X_scaled)
else:
    X_2d = X_scaled.copy()

plot_2d(X_2d, title=f"Input data ({data_label})", save_name="input_data.png")

# ----------------------------
# 1) Classical simple clustering algorithm (threshold-based)
# ----------------------------
def classical_threshold_clustering(X, T):
    """
    Simple one-pass clustering:
    - first point becomes center of first cluster
    - for each next point, compute distance to each existing center,
      if min distance <= T -> add to that cluster (and update center)
      else create new cluster with center = the point
    Returns: labels array, centers list
    """
    X = np.asarray(X)
    centers = []
    labels = -1 * np.ones(X.shape[0], dtype=int)
    cluster_counts = []
    for i, x in enumerate(X):
        if len(centers) == 0:
            centers.append(x.copy())
            labels[i] = 0
            cluster_counts.append(1)
            continue
        dists = np.linalg.norm(np.vstack(centers) - x, axis=1)
        jmin = np.argmin(dists)
        if dists[jmin] <= T:
            # assign to cluster jmin and update center (running average)
            c = cluster_counts[jmin]
            centers[jmin] = (centers[jmin] * c + x) / (c + 1)
            cluster_counts[jmin] += 1
            labels[i] = jmin
        else:
            # new cluster
            centers.append(x.copy())
            cluster_counts.append(1)
            labels[i] = len(centers) - 1
    centers = np.vstack(centers)
    return labels, centers

# Run classical algorithm for several T values and show characteristics
classical_results = {}
for T in T_values:
    labels_c, centers_c = classical_threshold_clustering(X_scaled, T)
    n_clusters = len(np.unique(labels_c))
    # silhouette requires at least 2 clusters and less than n_samples
    sil = None
    if 1 < n_clusters < n_samples:
        try:
            sil = silhouette_score(X_scaled, labels_c)
        except Exception:
            sil = None
    classical_results[T] = {"labels": labels_c, "centers": centers_c, "n_clusters": n_clusters, "silhouette": sil}
    print(f"[Classical T={T:.3f}] clusters={n_clusters}, silhouette={sil}")

# Visualize a couple of results (min, median, max clusters)
sorted_by_clusters = sorted(classical_results.items(), key=lambda kv: kv[1]['n_clusters'])
for T, res in sorted_by_clusters[:3]:
    plot_2d(X_2d, labels=res['labels'], centers=PCA(n_components=2).fit_transform(scaler.inverse_transform(res['centers'])) if n_features>2 else res['centers'],
            title=f"Classical clustering T={T:.2f} | clusters={res['n_clusters']}",
            save_name=f"classical_T_{T:.2f}.png")

# ----------------------------
# 2) K-means experiments (three initialization variants)
# ----------------------------
def kmeans_with_init_strategy(X, n_clusters, strategy="random", repeat=1, random_state=None):
    """
    Strategies:
      - "first_p": choose first p points as init centers
      - "random": random selection of p points from dataset (scikit-learn default)
      - "nearby_p": pick a random point, then pick p points nearest to it (simulates choosing p points from one cluster)
    Returns a list of results per repeat:
      {"labels":..., "inertia":..., "silhouette":..., "centers":..., "init_idx":...}
    """
    results = []
    rng = np.random.RandomState(random_state)
    n = X.shape[0]
    for r in range(repeat):
        if strategy == "first_p":
            init_idx = list(range(n_clusters))
            init = X[init_idx]
            km = KMeans(n_clusters=n_clusters, init=init, n_init=1, random_state=rng.randint(0,1e6))
        elif strategy == "nearby_p":
            base = rng.randint(0, n)
            # compute distances in original scaled space
            d = np.linalg.norm(X - X[base], axis=1)
            init_idx = np.argsort(d)[:n_clusters]
            init = X[init_idx]
            km = KMeans(n_clusters=n_clusters, init=init, n_init=1, random_state=rng.randint(0,1e6))
        elif strategy == "random":
            # let sklearn pick randomly; but to make deterministic, pick random sample centers
            init_idx = rng.choice(n, size=n_clusters, replace=False)
            init = X[init_idx]
            km = KMeans(n_clusters=n_clusters, init=init, n_init=1, random_state=rng.randint(0,1e6))
        else:
            raise ValueError("Unknown strategy")
        km.fit(X)
        labels = km.labels_
        inertia = km.inertia_
        sil = None
        if 1 < n_clusters < n:
            try:
                sil = silhouette_score(X, labels)
            except Exception:
                sil = None
        results.append({
            "labels": labels,
            "centers": km.cluster_centers_,
            "inertia": inertia,
            "silhouette": sil,
            "init_idx": init_idx
        })
    return results

kmeans_strategies = ["first_p", "nearby_p", "random"]
kmeans_summary = {}

for strat in kmeans_strategies:
    res_list = kmeans_with_init_strategy(X_scaled, K, strategy=strat, repeat=KMEANS_REPEATS, random_state=RANDOM_STATE)
    # collect summary stats
    inertias = [r["inertia"] for r in res_list]
    sils = [r["silhouette"] for r in res_list if r["silhouette"] is not None]
    print(f"KMeans strategy={strat} | inertia mean={np.mean(inertias):.3f} std={np.std(inertias):.3f} | silhouette mean={(np.mean(sils) if sils else None)}")
    kmeans_summary[strat] = res_list

# Visualize best run per strategy by inertia
for strat, runs in kmeans_summary.items():
    best = min(runs, key=lambda r: r['inertia'])
    centers = best['centers']
    labels = best['labels']
    # convert centers to 2D plot coordinates
    if n_features > 2:
        centers_plot = pca.transform(scaler.inverse_transform(centers))
    else:
        centers_plot = centers
    plot_2d(X_2d, labels=labels, centers=centers_plot, title=f"KMeans {strat} best (inertia={best['inertia']:.2f})", save_name=f"kmeans_{strat}_best.png")

# ----------------------------
# 3) Neural network clustering (competitive learning / Kohonen-like very small SOM)
# ----------------------------
class CompetitiveKohonen:
    def __init__(self, n_units=3, n_features=None, lr=0.1, lr_decay=0.995, random_state=None):
        self.n_units = n_units
        self.lr0 = lr
        self.lr_decay = lr_decay
        self.random_state = np.random.RandomState(random_state)
        if n_features is None:
            raise ValueError("n_features required")
        # initialize weights randomly (small)
        self.weights = self.random_state.normal(scale=0.1, size=(n_units, n_features))

    def fit(self, X, epochs=100, verbose=False):
        X = np.asarray(X)
        lr = self.lr0
        # optionally normalize inputs for direction-based learning
        for ep in range(epochs):
            idxs = np.arange(X.shape[0])
            self.random_state.shuffle(idxs)
            for i in idxs:
                x = X[i]
                # find winner (closest by Euclidean)
                dists = np.linalg.norm(self.weights - x, axis=1)
                w = np.argmin(dists)
                # update winner weights towards x (Oja-like/simple)
                self.weights[w] += lr * (x - self.weights[w])
            lr *= self.lr_decay
            if verbose and (ep % (epochs//5 + 1) == 0):
                print(f"Epoch {ep}/{epochs} lr={lr:.4f}")
        return self

    def predict(self, X):
        d = np.linalg.norm(self.weights[None,:,:] - X[:,None,:], axis=2)  # shape n_samples x n_units
        labels = np.argmin(d, axis=1)
        return labels

# Run several experiments with different initial weight seeds
kohonen_experiments = {}
for seed in [0, 5, 42, 123]:
    model = CompetitiveKohonen(n_units=K, n_features=X_scaled.shape[1], lr=KOHO_LR0, lr_decay=KOHO_DECAY, random_state=seed)
    model.fit(X_scaled, epochs=KOHO_EPOCHS, verbose=False)
    labels_k = model.predict(X_scaled)
    sil = None
    try:
        if 1 < len(np.unique(labels_k)) < n_samples:
            sil = silhouette_score(X_scaled, labels_k)
    except Exception:
        sil = None
    kohonen_experiments[seed] = {"model": model, "labels": labels_k, "silhouette": sil}
    print(f"Kohonen seed={seed} clusters={len(np.unique(labels_k))} silhouette={sil}")

# Visualize one Kohonen result
for seed, res in list(kohonen_experiments.items())[:3]:
    labels = res['labels']
    # compute centers from assignments for plotting (in original scaled -> 2D)
    centers = np.array([X_scaled[labels == c].mean(axis=0) if np.any(labels==c) else np.zeros(X_scaled.shape[1]) for c in range(K)])
    if n_features > 2:
        centers_plot = pca.transform(scaler.inverse_transform(centers))
    else:
        centers_plot = centers
    plot_2d(X_2d, labels=labels, centers=centers_plot, title=f"Kohonen seed={seed} silhouette={res['silhouette']}", save_name=f"kohonen_seed_{seed}.png")

# ----------------------------
# 4) Save results (labels, centers) and produce a small report CSV
# ----------------------------
def save_assignments(labels, prefix):
    df_out = pd.DataFrame({
        "index": np.arange(len(labels)),
        "cluster": labels
    })
    path = os.path.join(SAVE_RESULTS_DIR, f"{prefix}_assignments.csv")
    df_out.to_csv(path, index=False)
    print(f"Saved assignments: {path}")

# Save best KMeans random run assignments
best_random = min(kmeans_summary["random"], key=lambda r: r["inertia"])
save_assignments(best_random["labels"], "kmeans_random_best")

# Save one Kohonen result
one_kohonen = list(kohonen_experiments.items())[0][1]
save_assignments(one_kohonen["labels"], "kohonen_seed0")

# Save classical for a chosen T (median T)
chosen_T = float(T_values[len(T_values)//2])
save_assignments(classical_results[chosen_T]["labels"], f"classical_T_{chosen_T:.2f}")

# ----------------------------
# 5) Short Conclusions printout (to include in report)
# ----------------------------
print("\n--- SHORT AUTOMATIC CONCLUSIONS ---")
print(f"Input: {data_label} | samples={n_samples} features={n_features}")
print("Classical algorithm (threshold):")
for T, info in list(classical_results.items())[:5]:
    print(f"  T={T:.3f} -> clusters={info['n_clusters']} silhouette={info['silhouette']}")
print("K-means strategies summary (sample):")
for strat, runs in kmeans_summary.items():
    print(f"  {strat}: best inertia={min(r['inertia'] for r in runs):.3f}")
print("Kohonen experiments (seeds):")
for seed, info in kohonen_experiments.items():
    print(f"  seed={seed} silhouette={info['silhouette']}")

print(f"\nAll generated plots and CSVs saved into directory: {SAVE_RESULTS_DIR}")
print("If you want, I can now:")
print(" - integrate your real Excel file columns (set FEATURE_COLS or ID_COL at top)")
print(" - create a PDF report summarizing figures and metrics")
print(" - tune K, thresholds, epochs, or add other distance metrics\n")

# End of script