# -*- coding: utf-8 -*-
"""Lab5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Nx7xC4bCviftz6HpVTDZS8ODiIiCAXUc
"""

# Full lab code: clustering (Lab 6_7) + classification MLP simulator (Lab 5)
# Paste the entire block into Google Colab and run.
# Requirements: pandas, numpy, matplotlib, sklearn (Colab already has these)

import os
import math
import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.cluster import KMeans
from sklearn.metrics import silhouette_score, accuracy_score
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA
from sklearn.model_selection import train_test_split

# ----------------------------
# Config / User parameters
# ----------------------------
EXCEL_PATHS = [
    "/content/Лаб6_7_6_кластер.xlsx",
    "/content/Лаб_6_7__Кластеризація.xlsx",
    "/mnt/data/Лаб6_7_6_кластер.xlsx",
    "/mnt/data/Лаб_6_7__Кластеризація.xlsx",
    "/content/Лаб6_7_6_кластер.xls",
    "/content/Лаб_6_7_6_кластер.xlsx",
    "/content/Лаб_6_7_6_кластер.xls"
]
SHEET_NAME = 0           # Excel sheet to read (0 or name)
FEATURE_COLS = None      # None => use all numeric columns
ID_COL = None            # optional id column name
SAVE_RESULTS_DIR = "/content/clustering_and_classification_results"
os.makedirs(SAVE_RESULTS_DIR, exist_ok=True)

# Clustering params
K = 3                   # target clusters for k-means & Kohonen (change per your variant)
T_values = np.linspace(0.5, 3.0, 12)  # threshold sweep for classical algorithm
KMEANS_REPEATS = 12
KOHO_EPOCHS = 250
KOHO_LR0 = 0.08
KOHO_DECAY = 0.995
RANDOM_STATE = 42

# MLP (classification lab) params
MLP_HIDDEN = [5]        # list defining hidden layers, e.g. [5] for one hidden layer with 5 neurons
MLP_LR = 0.1
MLP_EPOCHS = 2000
MLP_ALPHA = 1.0         # parameter alpha for sigmoid steepness (if used)

np.random.seed(RANDOM_STATE)
random.seed(RANDOM_STATE)

# ----------------------------
# Utilities
# ----------------------------
def try_load_excel(paths):
    for p in paths:
        if os.path.isfile(p):
            print(f"Loading Excel file: {p}")
            try:
                df = pd.read_excel(p, sheet_name=SHEET_NAME)
                return df, p
            except Exception as e:
                print("Failed to read", p, e)
    return None, None

def prepare_features(df, feature_cols=None):
    df_num = df.select_dtypes(include=[np.number]).copy()
    if feature_cols is not None:
        df_num = df_num[feature_cols]
    return df_num

def ensure_2d(X):
    X = np.asarray(X)
    if X.ndim == 1:
        X = X.reshape(-1, 1)
    return X

def save_fig(fig, name):
    path = os.path.join(SAVE_RESULTS_DIR, name)
    fig.savefig(path, bbox_inches="tight")
    print(f"Saved figure: {path}")

def plot_2d(X_2d, labels=None, centers=None, title="", save_name=None, cmap='tab10'):
    fig, ax = plt.subplots(figsize=(6,5))
    X = X_2d
    if labels is None:
        ax.scatter(X[:,0], X[:,1], s=30)
    else:
        unique = np.unique(labels)
        for u in unique:
            mask = labels == u
            ax.scatter(X[mask,0], X[mask,1], s=30, label=f"c{u}")
        ax.legend()
    if centers is not None:
        ax.scatter(centers[:,0], centers[:,1], marker='X', s=150, c='k', label='centers')
        ax.legend()
    ax.set_title(title)
    if save_name:
        save_fig(fig, save_name)
    plt.show()

# ----------------------------
# 0) Data loading (clustering dataset)
# ----------------------------
df_loaded, loaded_path = try_load_excel(EXCEL_PATHS)
if df_loaded is None:
    print("No Excel data found — generating synthetic example clustering data (3 clusters).")
    from sklearn.datasets import make_blobs
    X_raw, y_true = make_blobs(n_samples=180, centers=K, cluster_std=[0.6,0.5,0.7][:K], random_state=RANDOM_STATE)
    df = pd.DataFrame(X_raw, columns=["x1","x2"])
    data_label = "synthetic_clusters"
else:
    df_num = prepare_features(df_loaded, FEATURE_COLS)
    df = df_num.reset_index(drop=True)
    data_label = os.path.basename(loaded_path)

X = df.values
X = ensure_2d(X)
n_samples, n_features = X.shape
print(f"Loaded data ({data_label}) samples={n_samples} features={n_features}")

# standardize features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# 2D projection for plotting
if n_features > 2:
    pca = PCA(n_components=2, random_state=RANDOM_STATE)
    X_2d = pca.fit_transform(X_scaled)
else:
    X_2d = X_scaled.copy()

plot_2d(X_2d, title=f"Input data ({data_label})", save_name="input_data.png")

# ----------------------------
# 1) Classical simple threshold clustering (one-pass)
# ----------------------------
def classical_threshold_clustering(X, T):
    X = np.asarray(X)
    centers = []
    labels = -1 * np.ones(X.shape[0], dtype=int)
    cluster_counts = []
    for i, x in enumerate(X):
        if len(centers) == 0:
            centers.append(x.copy())
            labels[i] = 0
            cluster_counts.append(1)
            continue
        dists = np.linalg.norm(np.vstack(centers) - x, axis=1)
        jmin = int(np.argmin(dists))
        if dists[jmin] <= T:
            c = cluster_counts[jmin]
            centers[jmin] = (centers[jmin] * c + x) / (c + 1)
            cluster_counts[jmin] += 1
            labels[i] = jmin
        else:
            centers.append(x.copy())
            cluster_counts.append(1)
            labels[i] = len(centers) - 1
    centers = np.vstack(centers)
    return labels, centers

classical_results = {}
for T in T_values:
    labels_c, centers_c = classical_threshold_clustering(X_scaled, T)
    n_clust = len(np.unique(labels_c))
    sil = None
    if 1 < n_clust < n_samples:
        try:
            sil = silhouette_score(X_scaled, labels_c)
        except Exception:
            sil = None
    classical_results[T] = {"labels": labels_c, "centers": centers_c, "n_clusters": n_clust, "silhouette": sil}
    print(f"[Classical T={T:.3f}] clusters={n_clust} silhouette={sil}")

# Visualize representative classical results (min clusters, median, max)
sorted_T = sorted(classical_results.items(), key=lambda kv: kv[1]['n_clusters'])
for T, res in sorted_T[:3]:
    # project centers for plotting (if needed)
    if n_features > 2:
        centers_plot = pca.transform(scaler.inverse_transform(res['centers']))
    else:
        centers_plot = res['centers']
    plot_2d(X_2d, labels=res['labels'], centers=centers_plot, title=f"Classical T={T:.2f} clusters={res['n_clusters']}", save_name=f"classical_T_{T:.2f}.png")

# ----------------------------
# 2) K-means experiments (3 initialization strategies)
# ----------------------------
def kmeans_with_init_strategy(X, n_clusters, strategy="random", repeats=10, random_state=None):
    rng = np.random.RandomState(random_state)
    n = X.shape[0]
    results = []
    for r in range(repeats):
        if strategy == "first_p":
            if n_clusters > n:
                raise ValueError("n_clusters > n")
            init_idx = np.arange(n_clusters)
            init = X[init_idx]
            km = KMeans(n_clusters=n_clusters, init=init, n_init=1, random_state=rng.randint(0,1e6))
        elif strategy == "nearby_p":
            base = rng.randint(0, n)
            d = np.linalg.norm(X - X[base], axis=1)
            init_idx = np.argsort(d)[:n_clusters]
            init = X[init_idx]
            km = KMeans(n_clusters=n_clusters, init=init, n_init=1, random_state=rng.randint(0,1e6))
        elif strategy == "random":
            init_idx = rng.choice(n, size=n_clusters, replace=False)
            init = X[init_idx]
            km = KMeans(n_clusters=n_clusters, init=init, n_init=1, random_state=rng.randint(0,1e6))
        else:
            raise ValueError("Unknown strategy")
        km.fit(X)
        labels = km.labels_
        inertia = km.inertia_
        sil = None
        try:
            if 1 < n_clusters < n:
                sil = silhouette_score(X, labels)
        except Exception:
            sil = None
        results.append({"labels": labels, "centers": km.cluster_centers_, "inertia": inertia, "silhouette": sil, "init_idx": init_idx})
    return results

kmeans_strategies = ["first_p", "nearby_p", "random"]
kmeans_summary = {}
for strat in kmeans_strategies:
    res_list = kmeans_with_init_strategy(X_scaled, K, strategy=strat, repeats=KMEANS_REPEATS, random_state=RANDOM_STATE)
    inertias = [r["inertia"] for r in res_list]
    sils = [r["silhouette"] for r in res_list if r["silhouette"] is not None]
    print(f"KMeans strategy={strat} | inertia mean={np.mean(inertias):.3f} std={np.std(inertias):.3f} | silhouette mean={(np.mean(sils) if sils else None)}")
    kmeans_summary[strat] = res_list

# Visualize best run per strategy
for strat, runs in kmeans_summary.items():
    best = min(runs, key=lambda r: r['inertia'])
    labels = best['labels']
    centers = best['centers']
    if n_features > 2:
        centers_plot = pca.transform(scaler.inverse_transform(centers))
    else:
        centers_plot = centers
    plot_2d(X_2d, labels=labels, centers=centers_plot, title=f"KMeans {strat} best (inertia={best['inertia']:.2f})", save_name=f"kmeans_{strat}_best.png")

# ----------------------------
# 3) Competitive Kohonen-like (winner-takes-all) clustering
# ----------------------------
class CompetitiveKohonen:
    def __init__(self, n_units, n_features, lr=0.08, lr_decay=0.995, random_state=None):
        self.n_units = n_units
        self.lr0 = lr
        self.lr_decay = lr_decay
        self.rng = np.random.RandomState(random_state)
        # small random init across normalized space
        self.weights = self.rng.normal(scale=0.1, size=(n_units, n_features))

    def fit(self, X, epochs=200, verbose=False):
        X = np.asarray(X)
        lr = self.lr0
        for ep in range(epochs):
            idxs = np.arange(X.shape[0])
            self.rng.shuffle(idxs)
            for i in idxs:
                x = X[i]
                dists = np.linalg.norm(self.weights - x, axis=1)
                w = int(np.argmin(dists))
                self.weights[w] += lr * (x - self.weights[w])
            lr *= self.lr_decay
            if verbose and (ep % (epochs//5 + 1) == 0):
                print(f"Epoch {ep}/{epochs} lr={lr:.4f}")
        return self

    def predict(self, X):
        dists = np.linalg.norm(self.weights[None,:,:] - X[:,None,:], axis=2)
        labels = np.argmin(dists, axis=1)
        return labels

kohonen_experiments = {}
for seed in [0, 7, 42, 123]:
    model = CompetitiveKohonen(n_units=K, n_features=X_scaled.shape[1], lr=KOHO_LR0, lr_decay=KOHO_DECAY, random_state=seed)
    model.fit(X_scaled, epochs=KOHO_EPOCHS, verbose=False)
    labels_k = model.predict(X_scaled)
    sil = None
    try:
        if 1 < len(np.unique(labels_k)) < n_samples:
            sil = silhouette_score(X_scaled, labels_k)
    except Exception:
        sil = None
    kohonen_experiments[seed] = {"model": model, "labels": labels_k, "silhouette": sil}
    print(f"Kohonen seed={seed} clusters={len(np.unique(labels_k))} silhouette={sil}")

# Visualize a Kohonen result
for seed, res in list(kohonen_experiments.items())[:3]:
    labels = res['labels']
    centers = np.array([X_scaled[labels==c].mean(axis=0) if np.any(labels==c) else np.zeros(X_scaled.shape[1]) for c in range(K)])
    if n_features > 2:
        centers_plot = pca.transform(scaler.inverse_transform(centers))
    else:
        centers_plot = centers
    plot_2d(X_2d, labels=labels, centers=centers_plot, title=f"Kohonen seed={seed} silhouette={res['silhouette']}", save_name=f"kohonen_seed_{seed}.png")

# ----------------------------
# 4) Save assignments (CSV)
# ----------------------------
def save_assignments(labels, prefix):
    df_out = pd.DataFrame({"index": np.arange(len(labels)), "cluster": labels})
    path = os.path.join(SAVE_RESULTS_DIR, f"{prefix}_assignments.csv")
    df_out.to_csv(path, index=False)
    print(f"Saved assignments: {path}")

# Save KMeans random best and one Kohonen and one classical
best_random = min(kmeans_summary["random"], key=lambda r: r["inertia"])
save_assignments(best_random["labels"], "kmeans_random_best")
one_kohonen = list(kohonen_experiments.items())[0][1]
save_assignments(one_kohonen["labels"], "kohonen_seed0")
midT = float(T_values[len(T_values)//2])
save_assignments(classical_results[midT]["labels"], f"classical_T_{midT:.2f}")

# ----------------------------
# 5) MLP classifier simulation (Lab 5)
#    Simple feed-forward MLP with backprop for 2D datasets (for demonstration)
# ----------------------------
# We'll create or load classification 2D data. If Excel contained class labels, adapt accordingly.
# If the loaded dataframe has a 'label' column, use it; otherwise generate synthetic classification data.
label_col = None
if df_loaded is not None:
    # attempt to detect a label-like column
    for c in df_loaded.columns:
        if str(c).lower() in ("label","class","y","target"):
            label_col = c
            break

if label_col is None:
    print("No label column detected — generating synthetic 2D classification dataset (2 classes).")
    from sklearn.datasets import make_classification
    Xc, yc = make_classification(n_samples=300, n_features=2, n_redundant=0, n_clusters_per_class=1, n_classes=2, class_sep=1.2, random_state=RANDOM_STATE)
else:
    # use first two numeric columns as features and the label column
    dfc = df_loaded.select_dtypes(include=[np.number]).copy()
    cols = dfc.columns.tolist()
    if len(cols) < 2:
        raise ValueError("Need at least 2 numeric features for MLP demo")
    Xc = dfc[cols[:2]].values
    yc = df_loaded[label_col].values

# standardize
scaler_c = StandardScaler()
Xc_scaled = scaler_c.fit_transform(Xc)

# simple MLP implementation (softmax output for multi-class)
def sigmoid(z, alpha=1.0):
    return 1.0 / (1.0 + np.exp(-alpha * z))

def sigmoid_derivative(a, alpha=1.0):
    return alpha * a * (1.0 - a)

def softmax(z):
    e = np.exp(z - np.max(z, axis=1, keepdims=True))
    return e / e.sum(axis=1, keepdims=True)

def to_onehot(y):
    classes = np.unique(y)
    mapping = {v:i for i,v in enumerate(classes)}
    y_idx = np.array([mapping[v] for v in y])
    onehot = np.zeros((len(y), len(classes)))
    onehot[np.arange(len(y)), y_idx] = 1
    return onehot, mapping

# network architecture
n_inputs = Xc_scaled.shape[1]
n_outputs = len(np.unique(yc))
hidden_sizes = MLP_HIDDEN  # list
layers = [n_inputs] + hidden_sizes + [n_outputs]

# weights init
def init_weights(layers, seed=None):
    rng = np.random.RandomState(seed)
    weights = []
    biases = []
    for i in range(len(layers)-1):
        w = rng.normal(scale=0.1, size=(layers[i], layers[i+1]))
        b = np.zeros((1, layers[i+1]))
        weights.append(w)
        biases.append(b)
    return weights, biases

# forward pass
def forward(X, weights, biases, alpha=1.0):
    activations = [X]
    zs = []
    for i in range(len(weights)-1):
        z = activations[-1].dot(weights[i]) + biases[i]
        a = sigmoid(z, alpha=alpha)
        zs.append(z)
        activations.append(a)
    # last layer: linear + softmax
    z = activations[-1].dot(weights[-1]) + biases[-1]
    zs.append(z)
    a = softmax(z)
    activations.append(a)
    return activations, zs

# backprop
def backprop(X, y_onehot, weights, biases, alpha=1.0, lr=0.1):
    activations, zs = forward(X, weights, biases, alpha)
    grads_w = [np.zeros_like(w) for w in weights]
    grads_b = [np.zeros_like(b) for b in biases]

    # output delta (cross-entropy with softmax)
    delta = activations[-1] - y_onehot  # shape (n, n_outputs)
    grads_w[-1] = activations[-2].T.dot(delta) / X.shape[0]
    grads_b[-1] = np.mean(delta, axis=0, keepdims=True)

    # backprop through hidden layers
    for l in range(len(weights)-2, -1, -1):
        da = delta.dot(weights[l+1].T)
        a = activations[l+1]
        delta = da * sigmoid_derivative(a, alpha=alpha)
        grads_w[l] = activations[l].T.dot(delta) / X.shape[0]
        grads_b[l] = np.mean(delta, axis=0, keepdims=True)

    # update weights
    for i in range(len(weights)):
        weights[i] -= lr * grads_w[i]
        biases[i] -= lr * grads_b[i]
    return weights, biases

# training function
def train_mlp(X_train, y_train, layers, epochs=1000, lr=0.1, alpha=1.0, seed=None, verbose=False):
    weights, biases = init_weights(layers, seed=seed)
    y_onehot, mapping = to_onehot(y_train)
    for ep in range(epochs):
        weights, biases = backprop(X_train, y_onehot, weights, biases, alpha=alpha, lr=lr)
        if verbose and (ep % (epochs//5 + 1) == 0):
            activations, _ = forward(X_train, weights, biases, alpha=alpha)
            preds = np.argmax(activations[-1], axis=1)
            acc = np.mean(preds == np.array([list(mapping.keys())[list(mapping.values()).index(i)] for i in preds])) if False else None
            print(f"Epoch {ep}/{epochs}")
    return weights, biases, mapping

# Train-test split and run
X_train, X_test, y_train, y_test = train_test_split(Xc_scaled, yc, test_size=0.3, random_state=RANDOM_STATE, stratify=yc)
weights, biases, mapping = train_mlp(X_train, y_train, layers, epochs=MLP_EPOCHS, lr=MLP_LR, alpha=MLP_ALPHA, seed=RANDOM_STATE, verbose=False)

# evaluate on test
activations_test, _ = forward(X_test, weights, biases, alpha=MLP_ALPHA)
y_pred = np.argmax(activations_test[-1], axis=1)
# convert mapping: mapping maps class_value->index; need inverse
inv_map = {v:k for k,v in mapping.items()}
y_pred_labels = np.array([inv_map[i] for i in y_pred])
acc = accuracy_score(y_test, y_pred_labels)
print(f"MLP Test accuracy: {acc:.4f}")

# Decision region plot over a grid
def plot_decision_region(X, weights, biases, mapping, scaler, title="Decision regions", save_name=None, grid_step=0.02):
    # build grid in original scaled coordinates
    x_min, x_max = X[:,0].min()-1, X[:,0].max()+1
    y_min, y_max = X[:,1].min()-1, X[:,1].max()+1
    xx, yy = np.meshgrid(np.arange(x_min, x_max, grid_step), np.arange(y_min, y_max, grid_step))
    grid = np.c_[xx.ravel(), yy.ravel()]
    # forward (model was trained on scaled inputs already)
    acts, _ = forward(grid, weights, biases, alpha=MLP_ALPHA)
    preds = np.argmax(acts[-1], axis=1)
    Z = preds.reshape(xx.shape)
    fig, ax = plt.subplots(figsize=(7,6))
    ax.contourf(xx, yy, Z, alpha=0.3)
    # plot training points (unscaled back to grid? our grid is in scaled coords)
    # So plot scaled points:
    unique = np.unique(y_train)
    for c in unique:
        mask = y_train == c
        ax.scatter(X_train[mask,0], X_train[mask,1], label=f"train {c}", edgecolor='k', s=25)
    ax.set_title(title)
    ax.legend()
    if save_name:
        save_fig(fig, save_name)
    plt.show()

plot_decision_region(Xc_scaled, weights, biases, mapping, scaler_c, title="MLP decision regions (scaled coordinates)", save_name="mlp_decision_regions.png")

# ----------------------------
# 6) Brief auto-report printout
# ----------------------------
print("\n--- AUTOMATIC SUMMARY ---")
print(f"Dataset: {data_label} | samples={n_samples} features={n_features}")
print("Classical threshold clustering summary (sample):")
for T, info in list(classical_results.items())[:5]:
    print(f" T={T:.2f} clusters={info['n_clusters']} silhouette={info['silhouette']}")
print("KMeans strategy summary:")
for strat, runs in kmeans_summary.items():
    print(f" {strat}: best inertia={min(r['inertia'] for r in runs):.3f}")
print("Kohonen experiments (seeds):")
for seed, info in kohonen_experiments.items():
    print(f" seed={seed} silhouette={info['silhouette']}")
print(f"MLP test accuracy: {acc:.4f}")
print(f"All plots and CSVs saved to: {SAVE_RESULTS_DIR}")

# Save a short CSV summary
summary = {
    "dataset": data_label,
    "samples": n_samples,
    "features": n_features,
    "mlp_test_accuracy": acc
}
pd.DataFrame([summary]).to_csv(os.path.join(SAVE_RESULTS_DIR, "summary.csv"), index=False)
print("Saved summary CSV.")

# End of script